services:
  mariadb:
    image: mariadb:10.11
    container_name: wisiee-db
    restart: always
    environment:
      MARIADB_DATABASE: wisiee
      MARIADB_USER: wisiee
      MARIADB_PASSWORD: wisiee
      MARIADB_ROOT_PASSWORD: wisiee
    ports:
      - "13306:13306"
    volumes:
      - wisiee-db-data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: wisiee-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - wisiee-minio-data:/data

  minio-init:
    image: minio/mc:latest
    container_name: wisiee-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb --ignore-existing myminio/wisiee;
      mc policy set public myminio/wisiee;
      exit 0;
      "

  wisiee:
    image: wisiee-app:v0.0.1
    container_name: wisiee-app
    restart: always
    depends_on:
      - mariadb
      - minio
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  wisiee-db-data:
  wisiee-minio-data:
