services:
  mariadb:
    image: mariadb:10.11
    container_name: wisiee-db
    restart: always
    environment:
      MARIADB_DATABASE: wisiee
      MARIADB_USER: wisiee
      MARIADB_PASSWORD: wisiee
      MARIADB_ROOT_PASSWORD: wisiee
    ports:
      - "13306:13306"
    volumes:
      - wisiee-db-data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    container_name: wisiee-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - wisiee-minio-data:/data

  wisiee:
    image: wisiee-app:latest
    container_name: wisiee-app
    restart: always
    depends_on:
      - mariadb
      - minio
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  wisiee-db-data:
  wisiee-minio-data:
