server:
  servlet:
    context-path: /wisiee
  port: 8080
  forward-headers-strategy: framework
  error:
    include-stacktrace: never
  logging:
    level:
      root: INFO
      com.verdiance.wisiee: DEBUG


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true


spring:
  application:
    name: wisiee
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          google:
            authorization-uri: ${GOOGLE_AUTH_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            user-name-attribute: sub

app:
  oauth:
    google:
      revoke-uri: ${GOOGLE_LOGOUT_URI}
  config:
    sendRedirect: "http://localhost:5173/profile?content=ProfileEditContent"

s3:
  region: ${S3_REGION}
  endpoint: ${S3_ENDPOINT}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  path-style: ${S3_PATH_STYLE}