server:
  servlet:
    context-path: /wisiee
  port: 8080
  error:
    include-stacktrace: never
  log:
    debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true


spring:
  application:
    name: wisiee
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          google:
            authorization-uri: ${GOOGLE_AUTH_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
            user-name-attribute: sub

app:
  oauth:
    google:
      revoke-uri: ${GOOGLE_LOGOUT_URI}
  config:
    sendRedirect: "/wisiee/api/users/login/success"

s3:
  region: ${S3_REGION}
  endpoint: ${S3_ENDPOINT}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  path-style: ${S3_PATH_STYLE}